import { useEffect, useRef, useState } from "react";
import { Moon, Sun } from "lucide-react";
import { marked } from "marked";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { diffHunks, edgeChars, type Hunk } from "./lib/diff";
import { amendmentPdfName } from "./lib/content";
import "./index.css";

type IndexItem = { key: string; title: string };
type Content = { key: string; title: string; markdown: string };
type SearchResult = {
  key: string;
  title: string;
  matches: { line: string; snippet: string }[];
};
type Amendment = {
  number: string;
  title: string;
  assent_date: string;
  key_changes: string;
  status: string;
  has_bill: boolean;
  act_url: string;
  bill_url: string;
};

// The static payload from /content.json (dist/content.json on static hosts):
// all content embedded at build time, so the site needs no API server.
type ContentPayload = {
  generated: string;
  preamble: { key: string; title: string; markdown: string };
  index: IndexItem[];
  contents: Record<string, string>;
  amendments: Amendment[];
  act_texts: Record<string, string>;
  bill_texts: Record<string, string>;
};

// Date-browser data: generated by scripts/generate-history.ts into
// data/history/*.json, served at /history/* (dev server and dist both).
type HistoryState = { n: number; date: string; title: string };
type HistoryIndex = {
  generated: string;
  states: HistoryState[];
  versions: Record<string, number[]>; // key -> amendment numbers that changed it
  changes: Record<string, string[]>; // amendment number -> keys it changed
};
type HistoryFile = { from: number; text: string }[];

// Part keys in display order: part1..part22, then the lettered parts.
const PART_KEYS = [
  "part1", "part2", "part3", "part4", "part5", "part6", "part7", "part8", "part9",
  "part10", "part11", "part12", "part13", "part14", "part15", "part16", "part17",
  "part18", "part19", "part20", "part21", "part22",
  "part4a", "part9a", "part9b", "part14a",
];

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// Post-pass over marked's HTML: give every <h2>/<h3> a slugified id and wrap the
// text in a same-page anchor so clicking a heading sets the URL hash (deep links).
function withHeadingAnchors(html: string): string {
  return html.replace(/<h([23])>([^<]*)<\/h\1>/g, (_, level, text) => {
    const id = slugify(text);
    return id
      ? `<h${level} id="${id}"><a href="#${id}" class="heading-link">${text}</a></h${level}>`
      : `<h${level}>${text}</h${level}>`;
  });
}

function render(markdown: string): string {
  return withHeadingAnchors(marked.parse(markdown, { async: false }));
}

// Manifest numbers are zero-padded ("01"…"96", "097"…"106").
function padNumber(n: number): string {
  return n <= 96 ? String(n).padStart(2, "0") : String(n).padStart(3, "0");
}

// In-flight history-file fetches, shared across renders (module scope so a
// re-render can't lose track and re-fetch). See versionFile below.
const historyRequests = new Map<string, Promise<HistoryFile | null>>();

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

export function App() {
  const [tab, setTab] = useState<"constitution" | "amendments" | "dates">("constitution");
  const [preamble, setPreamble] = useState("");
  const [items, setItems] = useState<IndexItem[]>([]);
  const [selected, setSelected] = useState<Content | null>(null);
  const [error, setError] = useState("");
  const [query, setQuery] = useState("");
  const [results, setResults] = useState<SearchResult[] | null>(null);
  const [amendments, setAmendments] = useState<Amendment[]>([]);
  const [amendmentQuery, setAmendmentQuery] = useState("");
  const [contents, setContents] = useState<Record<string, string>>({});
  const [actTexts, setActTexts] = useState<Record<string, string>>({});
  const [billTexts, setBillTexts] = useState<Record<string, string>>({});

  // Amendments detail (git/text views) + date browser state.
  const [detail, setDetail] = useState<Amendment | null>(null);
  const [detailView, setDetailView] = useState<"text" | "git">("git");

  // Dark mode: mirrors the `dark` class on <html>. The inline head script sets
  // the class before first paint; this picks it up and the effect below keeps
  // class + localStorage in sync with the header toggle.
  const [dark, setDark] = useState(() => document.documentElement.classList.contains("dark"));
  useEffect(() => {
    document.documentElement.classList.toggle("dark", dark);
    localStorage.setItem("theme", dark ? "dark" : "light");
  }, [dark]);
  const [history, setHistory] = useState<HistoryIndex | null>(null);
  const [dateA, setDateA] = useState(today());
  const [dateB, setDateB] = useState("");
  const [historyCache, setHistoryCache] = useState<Record<string, HistoryFile>>({});
  const [openHistory, setOpenHistory] = useState<string | null>(null);
  const [compareOpen, setCompareOpen] = useState<string | null>(null);
  const [historyError, setHistoryError] = useState("");

  // Client-side twin of the server's /api/search: case-insensitive substring,
  // up to 5 matches per file, 20-file cap, sorted by match count. Runs over
  // the embedded contents map, so it works on static hosting with no API.
  const runSearch = (e: React.FormEvent) => {
    e.preventDefault();
    const q = query.trim();
    if (!q) {
      setResults(null); // query cleared → drop stale results
      return;
    }
    if (q.length < 2) {
      setResults([]); // mirrors the server's "query too short" → no matches
      return;
    }
    const needle = q.toLowerCase();
    const found: SearchResult[] = [];
    for (const [key, markdown] of Object.entries(contents)) {
      const matches: { line: string; snippet: string }[] = [];
      for (const line of markdown.split("\n")) {
        if (!line.toLowerCase().includes(needle)) continue;
        matches.push({ line, snippet: line.length > 140 ? `${line.slice(0, 140)}…` : line });
        if (matches.length === 5) break;
      }
      if (matches.length > 0) {
        found.push({ key, title: items.find(i => i.key === key)?.title ?? key, matches });
      }
    }
    found.sort((a, b) => b.matches.length - a.matches.length);
    setResults(found.slice(0, 20));
  };

  useEffect(() => {
    // One payload holds everything: preamble, index, full contents (reading
    // pane + search), amendments, act/bill texts. On static hosts this is
    // dist/content.json.
    fetch("/content.json")
      .then(res => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((data: ContentPayload) => {
        setPreamble(data.preamble.markdown);
        setItems(data.index);
        setContents(data.contents);
        setAmendments(data.amendments);
        setActTexts(data.act_texts);
        setBillTexts(data.bill_texts);
      })
      .catch(() => setError("Failed to load content.json — run the Bun server or rebuild"));
  }, []);

  // Date-browser index (also needed for amendment git views), fetched lazily.
  useEffect(() => {
    if (history || (tab !== "dates" && !detail)) return;
    fetch("/history/index.json")
      .then(res => (res.ok ? res.json() : Promise.reject(new Error(`HTTP ${res.status}`))))
      .then((data: HistoryIndex) => setHistory(data))
      .catch(() => setHistoryError("Failed to load the amendment history index — run scripts/generate-history.ts and rebuild"));
  }, [tab, detail, history]);

  const open = (item: IndexItem) => {
    const markdown = contents[item.key];
    if (markdown === undefined) return;
    setSelected({ key: item.key, title: item.title, markdown });
  };

  // Group the index into Parts (explicit display order) and Schedules (numeric).
  const parts = items
    .filter(item => PART_KEYS.includes(item.key))
    .sort((a, b) => PART_KEYS.indexOf(a.key) - PART_KEYS.indexOf(b.key));
  const schedules = items
    .filter(item => /^schedule\d+$/.test(item.key))
    .sort((a, b) => Number(a.key.slice(8)) - Number(b.key.slice(8)));

  const indexButtons = (group: IndexItem[], onPick?: (item: IndexItem) => void) => (
    <div className="mt-2 grid grid-cols-2 items-start gap-2 md:grid-cols-4">
      {group.map(item => (
        <Button
          key={item.key}
          variant="outline"
          className="h-auto min-w-0 justify-start py-2 text-left text-xs leading-snug whitespace-normal"
          onClick={() => (onPick ? onPick(item) : open(item))}
        >
          {item.title}
        </Button>
      ))}
    </div>
  );

  // --- Date browser helpers ---

  // Latest state whose amendment date is <= the given date (state 0 = original).
  // Assent dates are NOT monotonic in amendment number (e.g. the 25th was
  // assented after the 26th), so this is a max scan, not a first-break.
  const stateForDate = (date: string): number => {
    if (!history) return 0;
    let n = 0;
    for (const s of history.states) {
      if (s.date <= date) n = s.n;
    }
    return n;
  };

  const stateMeta = (n: number): HistoryState | undefined =>
    history?.states.find(s => s.n === n);

  // Keys present at state n (the part/schedule existed by then).
  const keysAtState = (n: number): string[] =>
    history
      ? Object.entries(history.versions)
          .filter(([, froms]) => froms.some(f => f <= n))
          .map(([key]) => key)
      : [];

  // One fetch per key, ever, per session: successful entries stay in the map
  // (not just while in flight) so a render that commits between a fetch's
  // resolution and its state update can never start a second request. Only
  // failures are dropped, allowing a later retry.
  const versionFile = (key: string): Promise<HistoryFile | null> => {
    const cached = historyCache[key];
    if (cached) return Promise.resolve(cached);
    const inFlight = historyRequests.get(key);
    if (inFlight) return inFlight;
    const request = fetch(`/history/${key}.json`)
      .then(res => (res.ok ? res.json() : Promise.reject(new Error(`HTTP ${res.status}`))))
      .then((data: HistoryFile) => {
        setHistoryCache(prev => ({ ...prev, [key]: data }));
        return data;
      })
      .catch(() => {
        historyRequests.delete(key);
        return null;
      });
    historyRequests.set(key, request);
    return request;
  };

  const textAtState = async (key: string, n: number): Promise<string | null> => {
    const file = await versionFile(key);
    if (!file) return null;
    let text: string | null = null;
    for (const v of file) if (v.from <= n) text = v.text;
    return text;
  };

  // Amendments that changed `key` up to and including state n (for the chips).
  const changedBy = (key: string, n: number): number[] =>
    (history?.versions[key] ?? []).filter(f => f <= n);

  const openAmendment = (n: number) => {
    const a = amendments.find(x => x.number === padNumber(n));
    if (a) {
      setDetail(a);
      setDetailView("git");
      setTab("amendments");
    }
  };

  const renderHistoryText = (text: string) => (
    <pre className="text-foreground max-h-[70vh] max-w-prose overflow-y-auto whitespace-pre-wrap pr-4 font-serif text-[13px] leading-relaxed">
      {text}
    </pre>
  );

  // --- Diff rendering (git views + compare) ---

  const DiffBlock = ({ title, aText, bText, note }: { title: string; aText: string | null; bText: string | null; note?: string }) => {
    if (!aText && !bText) return null;
    if (!aText) {
      // whole file added
      const lines = (bText ?? "").split("\n");
      return (
        <div className="rounded border text-xs">
          <div className="border-b bg-muted px-2 py-1 font-mono font-medium">{title} <span className="text-green-700 dark:text-green-400">(+{lines.length})</span></div>
          <pre className="max-h-80 overflow-y-auto p-2">
            {lines.map((l, i) => (
              <div key={i} className="bg-green-50 dark:bg-green-950/50 px-1">
                <span className="text-green-700 dark:text-green-400 select-none">+ </span>{l || " "}
              </div>
            ))}
          </pre>
        </div>
      );
    }
    if (!bText) {
      const lines = aText.split("\n");
      return (
        <div className="rounded border text-xs">
          <div className="border-b bg-muted px-2 py-1 font-mono font-medium">{title} <span className="text-red-700 dark:text-red-400">(−{lines.length})</span></div>
          <pre className="max-h-80 overflow-y-auto p-2">
            {lines.map((l, i) => (
              <div key={i} className="bg-red-50 dark:bg-red-950/50 px-1">
                <span className="text-red-700 dark:text-red-400 select-none">- </span>{l || " "}
              </div>
            ))}
          </pre>
        </div>
      );
    }
    const hunks = diffHunks(aText, bText);
    const stats = hunks.reduce(
      (acc, h) => ({ del: acc.del + h.del.length, add: acc.add + h.add.length }),
      { del: 0, add: 0 },
    );
    if (stats.del + stats.add === 0) return null;
    return (
      <div className="rounded border text-xs">
        <div className="border-b bg-muted px-2 py-1 font-mono font-medium">
          {title}{" "}
          <span className="text-green-700 dark:text-green-400">+{stats.add}</span>{" "}
          <span className="text-red-700 dark:text-red-400">−{stats.del}</span>
        </div>
        <div className="max-h-[60vh] overflow-y-auto whitespace-pre-wrap p-2 font-mono">
          {hunks.map((h, hi) => (
            <div key={hi} className="mb-2">
              {h.ctx.map((l, i) => (
                <div key={i} className="text-muted-foreground px-1">
                  <span className="select-none">  </span>{l.text || " "}
                </div>
              ))}
              {h.del.map((l, i) => (
                <div key={`d${i}`} className="bg-red-50 dark:bg-red-950/50 px-1">
                  <span className="text-red-700 dark:text-red-400 select-none">- </span>
                  <Highlighted side="del" line={l.text} pair={h.add[i]?.text ?? ""} />
                </div>
              ))}
              {h.add.map((l, i) => (
                <div key={`a${i}`} className="bg-green-50 dark:bg-green-950/50 px-1">
                  <span className="text-green-700 dark:text-green-400 select-none">+ </span>
                  <Highlighted side="add" line={l.text} pair={h.del[i]?.text ?? ""} />
                </div>
              ))}
            </div>
          ))}
        </div>
      </div>
    );
  };

  const Highlighted = ({ side, line, pair }: { side: "del" | "add"; line: string; pair: string }) => {
    const { pre, post } = edgeChars(line, pair);
    const mid = line.length - pre - post;
    if (mid <= 0) return <>{line || " "}</>;
    const cls = side === "del" ? "bg-red-200 dark:bg-red-900/60" : "bg-green-200 dark:bg-green-900/60";
    return (
      <>
        {line.slice(0, pre)}
        <span className={cls}>{line.slice(pre, pre + mid)}</span>
        {line.slice(pre + mid)}
      </>
    );
  };

  // --- Amendment detail (Text / Git views) ---

  const amendmentDetail = detail && (
    <Card>
      <CardHeader className="space-y-1">
        <Button variant="ghost" size="sm" className="-ml-2 w-fit" onClick={() => setDetail(null)}>
          ← All amendments
        </Button>
        <CardTitle className="text-lg">
          <span className="text-muted-foreground font-mono text-sm">{detail.number}</span> {detail.title}
        </CardTitle>
        <p className="text-muted-foreground text-sm">
          Assented {detail.assent_date}
          {detail.status === "MISSING_BILL" && <span className="italic"> · bill text not available (lost before 1997)</span>}
        </p>
        {detail.key_changes && <p className="text-muted-foreground text-sm">{detail.key_changes}</p>}
        <div className="flex flex-wrap gap-2 pt-1">
          <Button asChild variant="outline" size="sm">
            <a href={`/amendments/${amendmentPdfName("act", Number(detail.number))}`} target="_blank" rel="noopener">
              Act PDF
            </a>
          </Button>
          {detail.has_bill && (
            <Button asChild variant="outline" size="sm">
              <a href={`/amendments/${amendmentPdfName("bill", Number(detail.number))}`} target="_blank" rel="noopener">
                Bill PDF
              </a>
            </Button>
          )}
          <div className="ml-auto flex gap-1">
            <Button size="sm" variant={detailView === "text" ? "default" : "outline"} onClick={() => setDetailView("text")}>
              Text
            </Button>
            <Button size="sm" variant={detailView === "git" ? "default" : "outline"} onClick={() => setDetailView("git")}>
              Git diff
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        {detailView === "text" ? (
          <AmendmentText amendment={detail} />
        ) : (
          <AmendmentGit amendment={detail} />
        )}
      </CardContent>
    </Card>
  );

  function AmendmentText({ amendment }: { amendment: Amendment }) {
    const text = actTexts[amendment.number];
    const billText = billTexts[amendment.number];
    if (!text && !billText) {
      return (
        <p className="text-muted-foreground text-sm">
          No machine-readable text is available for this document (scan-only PDF) — download the PDF above.
        </p>
      );
    }
    return (
      <div className="space-y-4">
        {text ? (
          <div>
            <h3 className="text-muted-foreground mb-1 text-xs font-semibold uppercase">Act — as enacted</h3>
            {renderHistoryText(text)}
          </div>
        ) : (
          <p className="text-muted-foreground text-sm">Act text unavailable (scan-only PDF).</p>
        )}
        {billText && (
          <div>
            <h3 className="text-muted-foreground mb-1 text-xs font-semibold uppercase">Bill — as introduced</h3>
            {renderHistoryText(billText)}
          </div>
        )}
      </div>
    );
  };

  function AmendmentGit({ amendment }: { amendment: Amendment }) {
    const n = Number(amendment.number);
    const keys = history?.changes[n] ?? [];
    if (!history) {
      return <p className="text-muted-foreground text-sm">Loading history…</p>;
    }
    if (keys.length === 0) {
      return (
        <p className="text-muted-foreground text-sm">
          No file changes are recorded in this archive for amendment {n} — the historical bundles did not
          capture them. The <span className="font-medium">Text</span> tab shows what the Act itself did.
        </p>
      );
    }
    return (
      <div className="space-y-4">
        <p className="text-muted-foreground text-xs">
          What the {n === 1 ? "1st" : n === 2 ? "2nd" : n === 3 ? "3rd" : `${n}th`} Amendment changed in the
          Constitution text — archive diff between state {n - 1} and state {n}.
        </p>
        {keys.map(key => (
          <AsyncDiff key={key} title={items.find(i => i.key === key)?.title ?? key} keyName={key} a={n - 1} b={n} />
        ))}
      </div>
    );
  };

  function AsyncDiff({ title, keyName, a, b }: { title: string; keyName: string; a: number; b: number }) {
    const [state, setState] = useState<{ a: string | null; b: string | null } | null>(null);
    const resolved = useRef<string | null>(null);
    useEffect(() => {
      const pair = `${a}:${b}`;
      if (resolved.current === pair) return; // already rendered for this state pair
      let alive = true;
      (async () => {
        const [ta, tb] = await Promise.all([textAtState(keyName, a), textAtState(keyName, b)]);
        if (alive) {
          setState({ a: ta, b: tb });
          resolved.current = pair;
        }
      })();
      return () => {
        alive = false;
      };
    }, [keyName, a, b, historyCache]);
    if (!state) return <p className="text-muted-foreground text-xs">Loading {title}…</p>;
    const block = <DiffBlock title={title} aText={state.a} bText={state.b} />;
    return block ?? <p className="text-muted-foreground text-xs">No change recorded for {title}.</p>;
  };

  // --- Date browser ---

  const nA = stateForDate(dateA);
  const nB = dateB ? stateForDate(dateB) : null;
  const metaA = stateMeta(nA);
  const metaB = nB !== null ? stateMeta(nB) : null;

  const dateBrowser = (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Constitution as of a date</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex flex-wrap items-end gap-4">
            <label className="text-sm">
              <span className="text-muted-foreground block text-xs">As of</span>
              <Input type="date" value={dateA} min="1950-01-26" max={today()} onChange={e => setDateA(e.target.value)} className="mt-1 w-44" />
            </label>
            <label className="text-sm">
              <span className="text-muted-foreground block text-xs">Compare with (optional)</span>
              <Input type="date" value={dateB} min="1950-01-26" max={today()} onChange={e => setDateB(e.target.value)} className="mt-1 w-44" />
              {dateB && (
                <button className="text-muted-foreground mt-1 text-xs underline" onClick={() => setDateB("")}>
                  clear
                </button>
              )}
            </label>
          </div>
          {historyError && <p className="text-destructive text-sm">{historyError}</p>}
          {metaA && (
            <p className="text-sm">
              As of <span className="font-medium">{dateA}</span> — the Constitution as amended by the{" "}
              <button className="text-primary underline" onClick={() => openAmendment(metaA.n)}>
                {metaA.n === 0 ? "original version" : `${metaA.n === 1 ? "1st" : metaA.n === 2 ? "2nd" : metaA.n === 3 ? "3rd" : `${metaA.n}th`} Amendment`}
              </button>{" "}
              ({metaA.title.split("Act, ")[1] ?? metaA.title}, assented {metaA.date}).
            </p>
          )}
          {nB !== null && metaA && metaB && nB !== nA && (
            <p className="text-sm">
              Comparing with <span className="font-medium">{dateB}</span> (after the {metaB.n === 1 ? "1st" : metaB.n === 2 ? "2nd" : metaB.n === 3 ? "3rd" : `${metaB.n}th`} Amendment).
            </p>
          )}
        </CardContent>
      </Card>

      {nB !== null && metaA && metaB && nB !== nA && (
        <ComparePanel nA={nA} nB={nB} />
      )}

      {(!nB || nB === nA) && (
        <Card>
          <CardHeader>
            <CardTitle>Parts &amp; Schedules — {dateA}</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {history ? (
              <>
                <div>
                  <h2 className="text-sm font-semibold">Parts</h2>
                  <div className="mt-2 space-y-1">
                    {parts.filter(p => keysAtState(nA).includes(p.key)).map(p => (
                      <div key={p.key} className="rounded border p-2">
                        <button
                          className="w-full text-left text-sm font-medium hover:underline"
                          onClick={() => setOpenHistory(openHistory === p.key ? null : p.key)}
                        >
                          {p.title}
                        </button>
                        {changedBy(p.key, nA).length > 0 && (
                          <p className="text-muted-foreground mt-1 text-xs">
                            amended by{" "}
                            {changedBy(p.key, nA).map(f => (
                              <button key={f} className="hover:text-primary underline inline-block py-0.5" onClick={() => openAmendment(f)}>
                                {f === 0 ? "orig" : f}
                              </button>
                            )).reduce<React.ReactNode[]>((acc, chip, i) => (i === 0 ? [chip] : [...acc, ", ", chip]), [])}
                          </p>
                        )}
                        {openHistory === p.key && <HistoryReader keyName={p.key} n={nA} />}
                      </div>
                    ))}
                  </div>
                </div>
                <div>
                  <h2 className="text-sm font-semibold">Schedules</h2>
                  <div className="mt-2 space-y-1">
                    {schedules.filter(s => keysAtState(nA).includes(s.key)).map(s => (
                      <div key={s.key} className="rounded border p-2">
                        <button
                          className="w-full text-left text-sm font-medium hover:underline"
                          onClick={() => setOpenHistory(openHistory === s.key ? null : s.key)}
                        >
                          {s.title}
                        </button>
                        {changedBy(s.key, nA).length > 0 && (
                          <p className="text-muted-foreground mt-1 text-xs">
                            amended by{" "}
                            {changedBy(s.key, nA).map(f => (
                              <button key={f} className="hover:text-primary underline inline-block py-0.5" onClick={() => openAmendment(f)}>
                                {f === 0 ? "orig" : f}
                              </button>
                            )).reduce<React.ReactNode[]>((acc, chip, i) => (i === 0 ? [chip] : [...acc, ", ", chip]), [])}
                          </p>
                        )}
                        {openHistory === s.key && <HistoryReader keyName={s.key} n={nA} />}
                      </div>
                    ))}
                  </div>
                </div>
              </>
            ) : (
              <p className="text-muted-foreground text-sm">Loading history…</p>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  );

  function HistoryReader({ keyName, n }: { keyName: string; n: number }) {
    const [text, setText] = useState<string | null>(null);
    const resolved = useRef<number | null>(null);
    useEffect(() => {
      if (resolved.current === n) return; // already rendered for this state
      let alive = true;
      textAtState(keyName, n).then(t => {
        if (alive) {
          setText(t);
          resolved.current = n;
        }
      });
      return () => {
        alive = false;
      };
    }, [keyName, n, historyCache]);
    if (text === null) return <p className="text-muted-foreground text-sm">Loading…</p>;
    if (text === undefined) return <p className="text-muted-foreground text-sm">Not in force at this date.</p>;
    return <div className="mt-3">{renderHistoryText(text)}</div>;
  };

  function ComparePanel({ nA, nB }: { nA: number; nB: number }) {
    const [files, setFiles] = useState<Record<string, { a: string | null; b: string | null }> | null>(null);
    const resolved = useRef<string | null>(null);
    useEffect(() => {
      const pair = `${nA}:${nB}`;
      if (resolved.current === pair) return; // already computed for this date pair
      let alive = true;
      (async () => {
        // A file's text differs between the two states iff a version boundary
        // falls strictly between them.
        const lo = Math.min(nA, nB);
        const hi = Math.max(nA, nB);
        const keys = history
          ? Object.keys(history.versions).filter(key => (history.versions[key] ?? []).some(f => f > lo && f <= hi))
          : [];
        const entries: Record<string, { a: string | null; b: string | null }> = {};
        const results = await Promise.all(
          keys.map(async key => [key, await textAtState(key, nA), await textAtState(key, nB)] as const),
        );
        for (const [key, ta, tb] of results) {
          if (alive && ta !== tb) entries[key] = { a: ta, b: tb };
        }
        if (alive) {
          setFiles(entries);
          resolved.current = pair;
        }
      })();
      return () => {
        alive = false;
      };
    }, [nA, nB, historyCache]);
    const list = files ? Object.entries(files) : null;
    return (
      <Card>
        <CardHeader>
          <CardTitle>
            Changes between {dateA} and {dateB}
            {list && <span className="text-muted-foreground text-sm font-normal"> — {list.length} file{list.length === 1 ? "" : "s"} differ</span>}
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          {list === null && <p className="text-muted-foreground text-sm">Loading…</p>}
          {list?.length === 0 && <p className="text-muted-foreground text-sm">No differences recorded.</p>}
          {list?.map(([key, v]) => (
            <div key={key}>
              <button
                className="hover:text-primary text-sm font-medium underline"
                onClick={() => setCompareOpen(compareOpen === key ? null : key)}
              >
                {items.find(i => i.key === key)?.title ?? key}
              </button>
              {compareOpen === key && (
                <div className="mt-2">
                  <DiffBlock title={items.find(i => i.key === key)?.title ?? key} aText={v.a} bText={v.b} />
                </div>
              )}
            </div>
          ))}
        </CardContent>
      </Card>
    );
  };

  return (
    <div className="mx-auto flex max-w-4xl flex-col gap-6 p-6">
      <header className="flex items-start justify-between gap-4">
        <div className="min-w-0">
          <h1 className="text-2xl font-bold sm:text-3xl">The Constitution of India</h1>
          <p className="text-muted-foreground text-sm">
            As amended up to the 106th Amendment (in force 16-04-2026)
          </p>
          <nav className="mt-3 flex flex-wrap gap-2">
            {(
              [
                ["constitution", "Constitution"],
                ["amendments", "Bills & Amendments"],
                ["dates", "By Date"],
              ] as const
            ).map(([id, label]) => (
              <Button key={id} variant={tab === id ? "default" : "outline"} size="sm" onClick={() => setTab(id)}>
                {label}
              </Button>
            ))}
          </nav>
        </div>
        <Button
          variant="outline"
          size="icon"
          onClick={() => setDark(!dark)}
          aria-label={dark ? "Switch to light mode" : "Switch to dark mode"}
          className="shrink-0"
        >
          {dark ? <Moon /> : <Sun />}
        </Button>
      </header>

      {error && <p className="text-destructive text-sm">{error}</p>}

      {tab === "constitution" && (
        <>
          <Card>
            <CardHeader>
              <CardTitle>Search</CardTitle>
            </CardHeader>
            <CardContent>
              <form className="flex gap-2" onSubmit={runSearch}>
                <Input
                  placeholder="Search the Constitution… e.g. secular, 330A, habeas corpus"
                  value={query}
                  onChange={e => setQuery(e.target.value)}
                />
                <Button type="submit">Search</Button>
              </form>
              {results && (
                results.length === 0 ? (
                  <p className="text-muted-foreground mt-4 text-sm">No matches</p>
                ) : (
                  <div className="mt-2 grid grid-cols-1 gap-2 md:grid-cols-2">
                    {results.map(r => (
                      <Button
                        key={r.key}
                        variant="outline"
                        className="h-auto justify-start py-2 text-left text-xs leading-snug"
                        onClick={() => open(r)}
                      >
                        <span className="min-w-0">
                          <span className="block truncate font-medium">{r.title}</span>
                          {r.matches[0] && (
                            <span className="text-muted-foreground block truncate">{r.matches[0].snippet}</span>
                          )}
                        </span>
                      </Button>
                    ))}
                  </div>
                )
              )}
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Preamble</CardTitle>
            </CardHeader>
            <CardContent>
              {preamble ? (
                // Trusted content: markdown is embedded from this repo's own files into /content.json.
                <div
                  className="markdown max-w-prose"
                  dangerouslySetInnerHTML={{ __html: render(preamble) }}
                />
              ) : (
                <p className="text-muted-foreground text-sm">Loading…</p>
              )}
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Parts &amp; Schedules</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <h2 className="text-sm font-semibold">Parts</h2>
                {indexButtons(parts)}
              </div>
              <div>
                <h2 className="text-sm font-semibold">Schedules</h2>
                {indexButtons(schedules)}
              </div>
            </CardContent>
          </Card>

          {selected && (
            <Card>
              <CardHeader>
                <CardTitle>{selected.title}</CardTitle>
              </CardHeader>
              <CardContent>
                <div
                  className="markdown max-h-[70vh] max-w-prose overflow-y-auto pr-4"
                  dangerouslySetInnerHTML={{ __html: render(selected.markdown) }}
                />
              </CardContent>
            </Card>
          )}
        </>
      )}

      {tab === "amendments" && (
        detail ? amendmentDetail : (
          <Card>
            <CardHeader>
              <CardTitle>Bills &amp; Amendments</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              <Input
                placeholder="Filter amendments… e.g. 105, women's reservation"
                value={amendmentQuery}
                onChange={e => setAmendmentQuery(e.target.value)}
              />
              <div className="max-h-[60vh] space-y-1 overflow-y-auto pr-1">
                {amendments
                  .filter(a => {
                    const q = amendmentQuery.trim().toLowerCase();
                    return (
                      q === "" ||
                      a.number.toLowerCase().includes(q) ||
                      a.title.toLowerCase().includes(q)
                    );
                  })
                  .map(a => (
                    <div
                      key={a.number}
                      className="flex items-start justify-between gap-2 border-b py-2 text-sm last:border-b-0"
                    >
                      <button className="min-w-0 text-left" onClick={() => setDetail(a)}>
                        <span className="text-muted-foreground font-mono text-xs">{a.number}</span>{" "}
                        <span className="font-medium leading-snug hover:underline">{a.title}</span>
                        {a.key_changes && (
                          <span className="text-muted-foreground line-clamp-2 block text-xs">
                            {a.key_changes}
                          </span>
                        )}
                        <span className="text-muted-foreground block text-xs">
                          {a.assent_date}
                          {a.status === "MISSING_BILL" && (
                            <span className="italic"> · bill missing</span>
                          )}
                        </span>
                      </button>
                      <div className="flex shrink-0 gap-1">
                        <Button asChild variant="outline" size="sm">
                          <a href={`/amendments/${amendmentPdfName("act", Number(a.number))}`} target="_blank" rel="noopener">
                            Act
                          </a>
                        </Button>
                        {a.has_bill && (
                          <Button asChild variant="outline" size="sm">
                            <a href={`/amendments/${amendmentPdfName("bill", Number(a.number))}`} target="_blank" rel="noopener">
                              Bill
                            </a>
                          </Button>
                        )}
                      </div>
                    </div>
                  ))}
              </div>
            </CardContent>
          </Card>
        )
      )}

      {tab === "dates" && dateBrowser}
    </div>
  );
}

export default App;
